# permissions for end users to view metricstorages.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: metricstorage-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: telemetry-operator
    app.kubernetes.io/part-of: telemetry-operator
    app.kubernetes.io/managed-by: kustomize
  name: metricstorage-viewer-role
rules:
- apiGroups:
  - telemetry.openstack.org
  resources:
  - metricstorages
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - telemetry.openstack.org
  resources:
  - metricstorages/status
  verbs:
  - get
