apiVersion: telemetry.openstack.org/v1beta1
kind: Autoscaling
metadata:
  labels:
    app.kubernetes.io/name: autoscaling
    app.kubernetes.io/instance: autoscaling-sample
    app.kubernetes.io/part-of: telemetry-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: telemetry-operator
  name: autoscaling
spec:
  enabled: true
  prometheus:
    deployPrometheus: false
  aodh:
    secret: osp-secret
    apiImage: "quay.io/podified-antelope-centos9/openstack-aodh-api:current-podified"
    evaluatorImage: "quay.io/podified-antelope-centos9/openstack-aodh-evaluator:current-podified"
    notifierImage: "quay.io/podified-antelope-centos9/openstack-aodh-notifier:current-podified"
    listenerImage: "quay.io/podified-antelope-centos9/openstack-aodh-listener:current-podified"
    passwordSelectors:
    databaseUser: aodh
    databaseInstance: openstack
    memcachedInstance: memcached
