apiVersion: telemetry.openstack.org/v1beta1
kind: MetricStorage
metadata:
  labels:
    app.kubernetes.io/name: metricstorage
    app.kubernetes.io/instance: metricstorage-sample
    app.kubernetes.io/part-of: telemetry-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: telemetry-operator
  name: metricstorage-sample
spec:
  redhatMetricStorage:
    type: prometheus
    alertingEnabled: true
    scrapeInterval: 30s
    storage:
      strategy: persistent
      retention: 24h
      persistent:
        pvcStorageRequest: 20G
