apiVersion: telemetry.openstack.org/v1beta1
kind: Telemetry
metadata:
  name: telemetry
  namespace: openstack
spec:
  ceilometer:
    centralImage: quay.io/podified-antelope-centos9/openstack-ceilometer-central:current-podified
    notificationImage: quay.io/podified-antelope-centos9/openstack-ceilometer-notification:current-podified
    sgCoreImage: quay.io/infrawatch/sg-core:latest
    computeImage: quay.io/podified-antelope-centos9/openstack-ceilometer-compute:current-podified
    ipmiImage: quay.io/podified-antelope-centos9/openstack-ceilometer-ipmi:current-podified
    nodeExporterImage: quay.io/prometheus/node-exporter:v1.5.0
  autoscaling:
    enabled: false
    prometheus:
      deployPrometheus: false
